# Generated by Django 3.1.3 on 2020-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField(default=0)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('creditcard', models.CharField(max_length=255)),
                ('income', models.IntegerField()),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('orderid', models.IntegerField()),
                ('orderdate', models.DateField()),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
